# 6. Decision Trees and Ensemble Learning

## 6.1 Data cleaning and prep

In [4]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [10]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-06-trees/CreditScoring.csv'

In [12]:
df = pd.read_csv(data)

In [14]:
df.head()

,Status,Seniority,Home,Time,Age,Marital,Records,Job,Expenses,Income,Assets,Debt,Amount,Price
0,1,9,1,60,30,2,1,3,73,129,0,0,800,846
1,1,17,1,60,58,3,1,1,48,131,0,0,1000,1658
2,2,10,2,36,46,2,2,3,90,200,3000,0,2000,2985
3,1,0,1,60,24,1,1,1,63,182,2500,0,900,1325
4,1,0,1,36,26,1,1,1,46,107,0,0,310,910

In [16]:
df.columns = df.columns.str.lower()

In [22]:
df.status.value_counts()

status
1    3200
2    1254
0       1
Name: count, dtype: int64

Convert the categorical variable values to their actual meanings. This is important to understand the data set we are working with.

In [24]:
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unk'
}

df.status = df.status.map(status_values)

home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignore',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

df.home = df.home.map(home_values)

marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

df.marital = df.marital.map(marital_values)

records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

df.records = df.records.map(records_values)

job_values = {
    1: 'fixed',
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

df.job = df.job.map(job_values)

In [26]:
df.head()

,status,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,ok,9,rent,60,30,married,no,freelance,73,129,0,0,800,846
1,ok,17,rent,60,58,widow,no,fixed,48,131,0,0,1000,1658
2,default,10,owner,36,46,married,yes,freelance,90,200,3000,0,2000,2985
3,ok,0,rent,60,24,single,no,fixed,63,182,2500,0,900,1325
4,ok,0,rent,36,26,single,no,fixed,46,107,0,0,310,910

Here, we see that the maximum value for income, assets, and det are 99999999 which is how the value was encoded to deal with missing value. We dont want them to interfer with the model so will replace the value with np.nan

In [31]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,763317.0,1060341.0,404382.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,8703625.0,10217569.0,6344253.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3500.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,166.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,99999999.0,99999999.0,99999999.0,5000.0,11140.0

In [34]:
for c in ['income', 'assets', 'debt']:
    df[c] = df[c].replace(to_replace=99999999, value=np.nan)

In [36]:
df.describe().round()

,seniority,time,age,expenses,income,assets,debt,amount,price
count,4455.0,4455.0,4455.0,4455.0,4421.0,4408.0,4437.0,4455.0,4455.0
mean,8.0,46.0,37.0,56.0,131.0,5403.0,343.0,1039.0,1463.0
std,8.0,15.0,11.0,20.0,86.0,11573.0,1246.0,475.0,628.0
min,0.0,6.0,18.0,35.0,0.0,0.0,0.0,100.0,105.0
25%,2.0,36.0,28.0,35.0,80.0,0.0,0.0,700.0,1118.0
50%,5.0,48.0,36.0,51.0,120.0,3000.0,0.0,1000.0,1400.0
75%,12.0,60.0,45.0,72.0,165.0,6000.0,0.0,1300.0,1692.0
max,48.0,72.0,68.0,180.0,959.0,300000.0,30000.0,5000.0,11140.0

Remove records where the target variable ('status') is unknow as we dont want these records.

In [39]:
df = df[df['status'] != 'unk'].reset_index(drop=True)

Now we do train test split to get the training data set, get the target variable out of the training data frame.

In [42]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [44]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [46]:
y_train = (df_train.status == 'default').astype('int').values
y_val = (df_val.status == 'default').astype('int').values
y_test = (df_test.status == 'default').astype('int').values

In [48]:
del df_train['status']
del df_val['status']
del df_test['status']

In [50]:
df_train.head()

,seniority,home,time,age,marital,records,job,expenses,income,assets,debt,amount,price
0,14,owner,60,30,married,no,fixed,60,70.0,4000.0,2800.0,600,1125
1,2,parents,60,35,married,no,fixed,75,104.0,0.0,0.0,1200,1677
2,8,rent,36,61,single,no,fixed,42,72.0,0.0,0.0,325,450
3,10,owner,36,46,married,yes,freelance,90,200.0,3000.0,0.0,2000,2985
4,2,other,60,41,separated,no,freelance,35,100.0,5000.0,0.0,1200,1450

## 6.2 Decision Trees

In [53]:
def assess_risk(client):
    if client['records'] == 'yes':
        if client['job'] == 'parttime':
            return 'default'
        else:
            return 'ok'
    else:
        if client['assets'] > 6000:
            return 'ok'
        else:
            return 'default'

In [55]:
xi = df_train.iloc[0].to_dict()

In [57]:
assess_risk(xi)

'default'

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text

In [61]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

In [63]:
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [65]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [67]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

The problem with decision tree with infinite depth is that it is prone to overfitting. The algorithm will remember the data and failed to generalize when encountering new data set. As seen below, the score on training data set is almost 1 whereas the score of validation dataset is only 0.65

In [71]:
y_pred = dt.predict_proba(X_val)[:, 1]
roc_auc_score(y_val, y_pred)

0.6541288315858125

In [73]:
y_pred = dt.predict_proba(X_train)[:, 1]
roc_auc_score(y_train, y_pred)

0.9999996473061242

We can control the max depth of the decision tree by tuning the hyper parameter of the DecisionTreeClassifier.

In [77]:
dt = DecisionTreeClassifier(max_depth=2)
dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [79]:
y_pred = dt.predict_proba(X_train)[:, 1]
auc = roc_auc_score(y_train, y_pred)
print('train:', auc)

y_pred = dt.predict_proba(X_val)[:, 1]
auc = roc_auc_score(y_val, y_pred)
print('val:', auc)

train: 0.7175133670978937
val: 0.7128913108914865

In [83]:
print(export_text(dt, feature_names=list(dv.get_feature_names_out())))

|--- seniority <= 2.50
|   |--- records=no <= 0.50
|   |   |--- class: 1
|   |--- records=no >  0.50
|   |   |--- class: 0
|--- seniority >  2.50
|   |--- records=no <= 0.50
|   |   |--- class: 0
|   |--- records=no >  0.50
|   |   |--- class: 0

In this tree with max_depth = 2 (2 layers), the first node is seniority and split by threshold = 2.5. Any records with seniority <= 2.5 will be on the left df. Then the left df is further split by records = no. On the right df, the df is split by records = no as well.

## 6.3 Decision Tree Algorithm

- Structure of a decision tree: A decision tree is a data structure composed of nodes (which contains conditions) and branches (which represent the value of a condition True or False). The tree starts with a root node, which is a parent of two other nodes, and each of these nodes can also be split into 2 others nodes and so one. At the last level of the tree, there are terminal nodes and they are called leaves.

- Depth of a decision tree: the depth of a tree is the number of the levels it has, or simple the length of the longest path from the root node to a leaf node.

- Rules and conditions, thresholds: The learning algorithm for a decision tree involes determining the best conditions to split the data at each node in order to achive the best possible classifier. When there are many features, the algorithm considers each feature with its optimized threshold to determine the best feature for splitting at a particular node. In essence, at each node, the algorithm evaluates all possible thresholds for every feature and calcultes the resulting misclassification rate. It then selects the condition (feature and threshold) that yields the lowest impurity.

- Misclassification rate: After each split, the goal is to divide the data into two sets that are as pure as possible. This means that the data within each set should belong predominantly to either one class, or the other. Another way to desribe this is to aim for the lowest possible misclassification rate (impurity). The misclassification rate is a weighted average of the error rates obtained after splitting the data into two sets. The predicted class for each set is determined by the majority class present in the set.

- Impurity criteria: Common miscalssification rate measurements are GINI impurity and Entropy. It is also possible to use MSE for regression problems.

- Decision trees can also be used to solve regression problems.

- Stopping criteria: The process of recursively splitting the data at each child node eventuallyu stops based on certain stopping criteria. These criteria prevent the model from overfitting and include:

  - The group is already pure or impurity rate is 0%
  - The maximum depth is reached (tree max depth).
  - The group is smaller than the minimum size set (min sample leaf).
  - The maximum number of leaves/terminal nodes has been reached.

In [87]:
data = [
    [8000, 'default'],
    [2000, 'default'],
    [   0, 'default'],
    [5000, 'ok'],
    [5000, 'ok'],
    [4000, 'ok'],
    [9000, 'ok'],
    [3000, 'default'],
]

df_example = pd.DataFrame(data, columns=['assets', 'status'])
df_example

   assets   status
0    8000  default
1    2000  default
2       0  default
3    5000       ok
4    5000       ok
5    4000       ok
6    9000       ok
7    3000  default

In [89]:
df_example.sort_values('assets')

   assets   status
2       0  default
1    2000  default
7    3000  default
5    4000       ok
3    5000       ok
4    5000       ok
0    8000  default
6    9000       ok

In [91]:
Ts = [0, 2000, 3000, 4000, 5000, 8000]

In [95]:
T = 4000
df_left = df_example[df_example.assets <= T]
df_right = df_example[df_example.assets > T]

display(df_left)
print(df_left.status.value_counts(normalize=True))
display(df_right)
print(df_left.status.value_counts(normalize=True))

   assets   status
1    2000  default
2       0  default
5    4000       ok
7    3000  default

status
default    0.75
ok         0.25
Name: proportion, dtype: float64

   assets   status
0    8000  default
3    5000       ok
4    5000       ok
6    9000       ok

status
default    0.75
ok         0.25
Name: proportion, dtype: float64